### ISSUE TITLE
关于Taro小程序monorepo问题

### ISSUE THREAD

**Issue by songxiaoliang** [kisstar/taro-issue-6411#1]
已解决

**Comment by kisstar** [comment]
:joy: 好久没跟 Taro 了，可能没太明白您的场景。按理在 monorepo 下每个 module 都是一个包，直接引入就可以了。可以提供一个 demo，这样可以一起看看、学习下

**Comment by songxiaoliang** [comment]
@kisstar 感谢，已解决
